### ISSUE TITLE
Suggestion - link github on image click

### ISSUE THREAD

**Issue by katbow** [tasminions/failures-and-champs#19]
The responsiveness is really good - only thing I noticed was the github links overlap when the screen gets smaller, so perhaps the images could be a link to github and the text link removed?

**Comment by eliasmalik** [comment]
Done, check the heroku again

**Comment by katbow** [comment]
The link is gone, but there's no link with the image when I click it.

**Comment by eliasmalik** [comment]
The link is on the name, but will add to the pic too.

**Comment by katbow** [comment]
Ahh okay. Cool, looks good without the link underneath :+1:
